services:
  postgres:
    image: postgres:17.5
    container_name: morphius_postgres
    environment:
      POSTGRES_DB: morphius
      POSTGRES_USER: morphius_user
      POSTGRES_PASSWORD: morphius_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  morphius-app:
    build: .
    container_name: morphius_app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    command: ["--api-key", "${API_KEY}", "--pg-url", "postgresql://morphius_user:morphius_password@postgres:5432/morphius?sslmode=disable"]
volumes:
  postgres_data:
